# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

def podsList
    # Pods for AssetExplorer
    pod 'CocoaLumberjack'
    pod 'MBProgressHUD'
    pod 'SDWebImage'
end

  # Pods for AssetExplorer
target 'AssetExplorer' do
    podsList
end
